kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka
  namespace: ocfev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      name: ocfev-kafka
